pub mod types;
pub mod embeddings;
pub mod store;
pub mod search;
pub mod manager;
pub mod watcher;
pub mod mmr;
pub mod query_expand;
pub mod embedding_cache;
pub mod auto_capture;

pub use types::*;
pub use embeddings::{EmbeddingProvider, create_embedding_provider};
pub use store::MemoryStore;
pub use search::{HybridSearchConfig, hybrid_search};
pub use manager::MemoryManager;
pub use mmr::{MmrConfig, mmr_rerank};
pub use query_expand::{build_fts5_query, extract_keywords, bm25_rank_to_score, has_cjk};
pub use embedding_cache::EmbeddingCache;
pub use auto_capture::{AutoCaptureConfig, CapturedMemory, CaptureCategory, should_capture, filter_by_config};
